# Generated by Django 3.2.7 on 2021-12-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('augusto@sandbox72f46b4c2b864d5ab2f3fd2435bb3ad5.mailgun.org', 'augusto@sandbox72f46b4c2b864d5ab2f3fd2435bb3ad5.mailgun.org'), ('test@test.com', 'test@test.com')], max_length=100)),
                ('to', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('1', 'pending'), ('2', 'sent'), ('3', 'failed')], default='1', max_length=1)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('json_response', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
