# Generated by Django 3.2.7 on 2021-12-16 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='sender',
            new_name='_from',
        ),
    ]
