# Generated by Django 3.2.7 on 2021-12-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_sender_email__from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='_from',
            field=models.CharField(choices=[('augusto@sandbox72f46b4c2b864d5ab2f3fd2435bb3ad5.mailgun.org', 'augusto@sandbox72f46b4c2b864d5ab2f3fd2435bb3ad5.mailgun.org'), ('test@mailgun.com', 'test@mailgun.com')], max_length=100),
        ),
    ]
